[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/minghaozou/pytorch-tutorial-with-solutions/blob/main/solutions/00_pytorch_fundamentals_exercises.ipynb)

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch


# Create random tensor
torch.manual_seed(0)
X = torch.randn(7,7)  # torch.randn draws from standard normal
X

tensor([[-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160],
        [-2.1152,  0.3223, -1.2633,  0.3500,  0.3081,  0.1198,  1.2377],
        [ 1.1168, -0.2473, -1.3527, -1.6959,  0.5667,  0.7935,  0.5988],
        [-1.5551, -0.3414,  1.8530,  0.7502, -0.5855, -0.1734,  0.1835],
        [ 1.3894,  1.5863,  0.9463, -0.8437, -0.6136,  0.8728,  1.0554],
        [ 0.1778, -0.2303, -0.3918,  0.5433, -0.3952,  0.2055,  0.7440],
        [ 1.5210,  3.4105, -1.5312, -1.2341,  1.8197, -0.5515, -1.3253]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
torch.manual_seed(0)
A = torch.randn(1, 7)

# Perform matrix multiplication
X @ A.T, (X @ A.T).shape

(tensor([[-3.1132],
         [-0.4052],
         [ 2.2938],
         [-4.9556],
         [-0.9954],
         [ 1.9452],
         [ 2.2410]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.randn(7, 7)

torch.manual_seed(0)
A = torch.randn(1, 7)

# Matrix multiply tensors
X @ A.T, (X @ A.T).shape

(tensor([[-3.1132],
         [-0.4052],
         [ 2.2938],
         [-4.9556],
         [-0.9954],
         [ 1.9452],
         [ 2.2410]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



*   `torch.manual_seed(seed)`

Seeds all RNGs: the default CPU RNG and all current CUDA devices.
This is usually what you want in 99% of cases.

*   `torch.cuda.manual_seed(seed)`

Seeds the CUDA RNG for the current GPU only (the one returned by `torch.cuda.current_device()`).


*   `torch.cuda.manual_seed_all(seed)`

Seeds the CUDA RNG for all GPUs on your system.


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [24]:
# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
torch.manual_seed(42)
tensor_A = torch.randn(2,3, device = 'cuda')

torch.manual_seed(42)
tensor_B = torch.randn(2,3, device = 'cuda')
tensor_A, tensor_B

(tensor([[ 0.1940,  2.1614, -0.1721],
         [ 0.8491, -1.9244,  0.6530]], device='cuda:0'),
 tensor([[ 0.1940,  2.1614, -0.1721],
         [ 0.8491, -1.9244,  0.6530]], device='cuda:0'))

In [25]:
# Create two random tensors on GPU
torch.cuda.manual_seed(1234)
X = torch.randn(2,3, device = 'cuda')

torch.cuda.manual_seed(1234)
A = torch.randn(2,3, device = 'cuda')
X, A

(tensor([[-1.6165,  0.5685, -0.5102],
         [-0.9113, -1.1555, -0.2262]], device='cuda:0'),
 tensor([[-1.6165,  0.5685, -0.5102],
         [-0.9113, -1.1555, -0.2262]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [28]:
# Perform matmul on tensor_A and tensor_B
tensor_X = tensor_A @ tensor_B.T
tensor_X, tensor_X.shape

(tensor([[ 4.7388, -4.1070],
         [-4.1070,  4.8506]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [30]:
# Find max
print(tensor_X.max())
# Find min
print(tensor_X.min())

tensor(4.8506, device='cuda:0')
tensor(-4.1070, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [31]:
# Find arg max
print(tensor_X.argmax())

# Find arg min
print(tensor_X.argmin())

tensor(3, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [32]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_A = torch.randn(1, 1, 1, 10)

# Remove single dimensions
tensor_B = tensor_A.squeeze()

# Print out tensors and their shapes
print(tensor_A)
print(tensor_A.shape)
print(tensor_B)
print(tensor_B.shape)

tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]])
torch.Size([1, 1, 1, 10])
tensor([-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,  1.2324,
         0.1382, -1.6822])
torch.Size([10])
